apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3twh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-3twh@sha256:8d26b4112866ee5508f5f73bdc1dd0877569f5e716f23b77880e1c2f2fdeb2d9
        name: my-nodejs
        resources: {}
status: {}
